# docker-compose.public.yml (Safe to share)
version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    image: ndukwearm19docker/arms-ui
    ports:
      - "3000:3000"

  backend:
    image: ndukwearm19docker/arms-flask-backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      # Other non-secret vars
    depends_on:
      - db